# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'test/SimpleAPI.Test/SimpleAPI.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'build Test: configuration $(buildConfiguration)'  

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/*/*.csproj'
  displayName: 'Run test for configuration $(buildConfiguration)' 

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '/home/vsts/work/_temp/*.trx'
    failTaskOnFailedTests: true  
  displayName: 'publish test results'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'build API: configuration $(buildConfiguration)'